[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_error.log

[program:nextjs-backend]
command=/bin/bash -c "cd /app && pm2 start npm --name backend -- start --port 3000 && pm2 logs"
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
user=node
directory=/app
stdout_logfile=/var/log/supervisor/nextjs.log
stderr_logfile=/var/log/supervisor/nextjs_error.log

[program:nextjs-frontend]
command=/bin/bash -c "cd /frontend && npm start"
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
user=node
directory=/frontend
stdout_logfile=/var/log/supervisor/frontend.log
stderr_logfile=/var/log/supervisor/frontend_error.log
